apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sample-runner
spec:
  replicas: 1
  template:
    spec:
      repository: ${GH_OWNER}/${GH_REPOSITORY}
      image: summerwind/actions-runner
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
